export default {
  bgImage: require("../Assets/Images/bgImage.jpeg"),
  icBack: require("../Assets/Images/ic_back.png"),
  icShow: require("../Assets/Images/ic_visible.png"),
  icHide: require("../Assets/Images/ic_hide.png"),
  icLoc: require("../Assets/Images/ic_loc.png"),
  icChat: require("../Assets/Images/ic_chat.png"),
  icCamera: require("../Assets/Images/ic_camera.png"),
  icPeople: require("../Assets/Images/ic_people.png"),
  icSearch: require("../Assets/Images/ic_search.png"),
  icAdd: require("../Assets/Images/ic_add.png"),
  icMore: require("../Assets/Images/ic_more.png"),
  icClose: require("../Assets/Images/close.png"),
  icNavigation: require("../Assets/Images/navigation.png"),
  icSetting: require("../Assets/Images/ic_setting.png"),
  //bitemoji
  emoji1: require("../Assets/Images/bitemoji/emoji1.png"),
  emoji2: require("../Assets/Images/bitemoji/emoji2.png"),
  emoji3: require("../Assets/Images/bitemoji/emoji3.png"),
  emoji4: require("../Assets/Images/bitemoji/emoji4.png"),
  emoji5: require("../Assets/Images/bitemoji/emoji5.png"),
};
